title: My Website
description: A landing page for my website
baseurl: ""

# Jekyll settings
permalink: pretty
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Navigation - keeping it empty until site is built out
navigation:
  - title: Home
    url: /
    
# Set as single page for now
defaults:
  - scope:
      path: ""
    values:
      layout: default