title: My Website
description: A landing page for my website
baseurl: ""
url: "https://deliberateallure.com"

# GitHub Pages settings
lsi: falseß
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Jekyll settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Navigation - keeping it empty until site is built out
navigation:
  - title: Home
    url: /
    
# Set as single page for now
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Explicitly include these files
include:
  - .htaccess
  - _pages
  - "*.html"
  - "*.css"
  - "*.js"
